name: cpu-${PROJECT_NAME_ENV}
services:
  core:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - PROJECT_NAME=${PROJECT_NAME_ENV}
      context: ../../
      dockerfile: environments/Dockerfile
    # env_file:
    #   - ../envs.env
    tty: true
    volumes:
        - ../../:/home/challenger/${PROJECT_NAME_ENV}