version: "3.8"

name: cpu-${PROJECT_NAME_ENV}
services:
  core:
    build:
      args:
        - BASE_IMAGE=ubuntu:20.04
        - PYTHON_VERSION=3.8
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - PROJECT_NAME=${PROJECT_NAME_ENV}
      context: ../../
      dockerfile: environments/Dockerfile
    # env_file:
    #   - ../envs.env
    tty: true
    volumes:
        - ../../:/home/challenger/${PROJECT_NAME_ENV}
    ports:
        - 8000:8000
